apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-auth-backend-module-guest-provider
  namespace: rhdh
  title: "Auth Backend Module Guest Provider"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/auth-backend-module-guest-provider
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/auth-backend-module-guest-provider
  tags:
    - authentication
spec:
  packageName: "@backstage/plugin-auth-backend-module-guest-provider"
  # Tag: bs_1.54.9__0.2.22
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-auth-backend-module-guest-provider@sha256:2f141379179944b07c1bbb602f63fc8d124b59d574d21196bcb8fc8bc21243cf"
  version: 0.2.22
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.6
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - backstage-plugin-auth-backend-module-guest-provider
  appConfigExamples:
    - title: Default configuration
      content:
        auth:
          providers:
            guest:
              dangerouslyAllowOutsideDevelopment: false
