apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-signals
  namespace: rhdh
  title: "Signals Frontend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/signals
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/signals
  tags: []
spec:
  packageName: "@backstage/plugin-signals"
  # Tag: bs_1.54.9__0.0.34
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-signals@sha256:ae40ff9660d1f864a564f8684362bf080f96ad295d7359cef527ed24bc2d488f"
  version: 0.0.34
  backstage:
    role: frontend-plugin
    supportedVersions: 1.54.6
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - signals-frontend
  appConfigExamples:
    - title: Default configuration (Signals registers the client API; no routes)
      content:
        dynamicPlugins:
          frontend:
            backstage.plugin-signals: {}
