apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-community-plugin-scaffolder-backend-module-kubernetes
  namespace: rhdh
  title: "Scaffolder Backend Module Kubernetes"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/community-plugins/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-backend-module-kubernetes
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/community-plugins/tree/main/workspaces/scaffolder-backend-module-kubernetes
  tags:
    - software-templates
spec:
  packageName: "@backstage-community/plugin-scaffolder-backend-module-kubernetes"
  # Tag: bs_1.54.6__2.21.0
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-scaffolder-backend-module-kubernetes@sha256:5cc3872fc039ca736a69f69d813a661068336a6d7761ce33eb61180cebeb2ae4"
  version: 2.21.0
  backstage:
    role: backend-plugin-module
    supportedVersions: 1.54.4
  author: Red Hat
  support: generally-available
  lifecycle: active
  partOf:
    - kubernetes-scaffolder-actions
  appConfigNotRequired: true
  appConfigExamples: []
