apiVersion: extensions.backstage.io/v1alpha1
kind: Package
metadata:
  name: backstage-plugin-notifications-backend
  namespace: rhdh
  title: "Notifications Backend"
  links:
    - url: https://red.ht/rhdh
      title: Homepage
    - url: https://github.com/backstage/backstage/issues
      title: Bugs
    - title: Source Code
      url: https://github.com/backstage/backstage/tree/master/plugins/notifications-backend
  annotations:
    backstage.io/source-location: url:https://github.com/backstage/backstage/tree/master/plugins/notifications-backend
  tags: []
spec:
  packageName: "@backstage/plugin-notifications-backend"
  # Tag: bs_1.54.9__0.6.8
  dynamicArtifact: "oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-notifications-backend@sha256:5ecdc49548a43cff7aef43f09f8cf5ac3b3df6971610f8b207b0a254c06e6988"
  version: 0.6.8
  backstage:
    role: backend-plugin
    supportedVersions: 1.54.6
  author: Red Hat
  support: tech-preview
  lifecycle: active
  appConfigExamples:
    - title: Default configuration
      content:
        notifications:
          concurrencyLimit: 10
  partOf:
    - notifications
